// One-shot migration: switch booking cancellation from DELETE to soft-delete.
//
// Changes:
//   1. Drop UNIQUE constraint on bookings.slot_id (so re-booking after cancel works)
//   2. Allow "cancelled" in bookings.status check constraint (text enum)
//   3. Add cancelled_at + cancelled_by columns
//   4. Add indexes on status and slot_id for analytics performance
//
// Idempotent — safe to re-run.
import { sql } from "drizzle-orm";
import { db } from "../lib/db";

async function main() {
  console.log("Starting migration: soft-delete cancellations");

  // 1. Drop the UNIQUE constraint on slot_id if present.
  // The constraint name was auto-generated by Drizzle as bookings_slot_id_unique
  await db.execute(sql`
    ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_slot_id_unique
  `);
  console.log("  ✓ Dropped UNIQUE on bookings.slot_id");

  // 2. Add the new columns (no-op if they already exist).
  await db.execute(sql`
    ALTER TABLE bookings
      ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone,
      ADD COLUMN IF NOT EXISTS cancelled_by text
  `);
  console.log("  ✓ Added cancelled_at + cancelled_by");

  // 3. Indexes for analytics queries (status group-bys, slot lookups).
  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS bookings_status_idx ON bookings (status)
  `);
  await db.execute(sql`
    CREATE INDEX IF NOT EXISTS "bookings_slotId_idx" ON bookings (slot_id)
  `);
  console.log("  ✓ Added indexes on status and slot_id");

  // 4. Verify the status column now accepts "cancelled". Drizzle stores enum
  //    types as plain text columns, so no DDL is needed for the enum widening
  //    (the check happens at the TypeScript layer). But if there's an existing
  //    CHECK constraint from a prior migration, drop and re-add to allow
  //    "cancelled". Drizzle didn't add one for text-with-enum, but be safe:
  await db.execute(sql`
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name LIKE '%bookings_status%'
      ) THEN
        EXECUTE (
          SELECT 'ALTER TABLE bookings DROP CONSTRAINT ' || quote_ident(constraint_name)
          FROM information_schema.check_constraints
          WHERE constraint_name LIKE '%bookings_status%'
          LIMIT 1
        );
      END IF;
    END $$;
  `);
  console.log("  ✓ Cleared any old status CHECK constraints");

  console.log("Migration complete.");
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
